name: SaWe
version: ${project.version}
description: Worldedit in eigenen Worldguard Regionen nutzen
website: https://github.com/pro-crafting/sawe
author: postremus
main: com.pro_crafting.mc.sawe.SaWe
depend: [WorldEdit, WorldGuard]
api-version: 1.15